### ISSUE TITLE
Create front-end mobile site

### ISSUE THREAD

**Issue by RobertTaylor94** [RobertTaylor94/Thryva#3]

**Comment by RobertTaylor94** [comment]
- [x] Added an initial mobile site

## To-Do
- [x] Add styles for larger screens
- [ ] Finalise content for cards

**Comment by RobertTaylor94** [comment]
- [x] Added an initial mobile site
- [x] Add styles for larger screens

## To-Do
- [ ] Finalise content for cards
- [ ] Update ID's for use with JS
